        "matched_exact": matched_exact,
        "matched_by_d": matched_by_d,
        "matched_fio_exact": matched_fio_exact,
        "matched_fio_fuzzy": matched_fio_fuzzy,
        "matched_fuzzy": matched_fuzzy,
        "unmatched_rows": unmatched_rows,
        "highlight_rows": highlight_rows,
        "passport_source_column": str(src_col),
        "fio_source_column": str(fio_col_ticket) if fio_col_ticket else None,
        "fuzzy_cutoff_percent": FUZZY_PASSPORT_SCORE_CUTOFF,
        "fuzzy_fio_cutoff_percent": FUZZY_FIO_SCORE_CUTOFF,